---
abstract: 'Class for random day generation'
author:
  - 'Michal Špaček <skim@cpan.org>'
build_requires:
  English: 0
  ExtUtils::MakeMaker: 6.36
  File::Object: 0.05
  Test::More: 0
  Test::NoWarnings: 0
  Test::Pod: 0
  Test::Pod::Coverage: 0
configure_requires:
  ExtUtils::MakeMaker: 6.36
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: bsd
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Random-Day
no_index:
  directory:
    - examples
    - inc
    - t
requires:
  Class::Utils: 0.03
  DateTime: 0
  DateTime::Event::Random: 0
  DateTime::Event::Recurrence: 0
  perl: 5.6.2
resources:
  bugtracker: https://rt.cpan.org/Public/Dist/Display.html?Name=Random-Day
  homepage: https://github.com/tupinek/Random-Day
  license: http://opensource.org/licenses/bsd-license.php
  repository: git://github.com/tupinek/Random-Day
version: 0.03
